import { Router } from "express";
import { forgotPassword, getStudentId, logout, resetStudentPassword, resetUserPassword, signIn, StudentSignIn, userForgotPassword, verifyStudentOtp, verifyUserOtp } from "./sign-in.service";
const signInRouter = Router();
signInRouter.post('/signIn',(req,res)=>signIn(req,res));
signInRouter.post('/StudentSignIn',(req,res)=>StudentSignIn(req,res));
signInRouter.get('/getStudentId/:id', (req, res) => getStudentId(req, res));
signInRouter.post('/logout/', (req, res) => logout(req, res));
signInRouter.post('/forgot-password',(req,res)=>forgotPassword(req,res));
signInRouter.post('/verifyStudentOtp',(req,res)=>verifyStudentOtp(req,res));
signInRouter.post('/resetStudentPassword',(req,res)=>resetStudentPassword(req,res));
signInRouter.post('/userForgotPassword',(req,res)=>userForgotPassword(req,res));
signInRouter.post('/verifyUserOtp',(req,res)=>verifyUserOtp(req,res));
signInRouter.post('/resetUserPassword',(req,res)=>resetUserPassword(req,res));
export default signInRouter;